package workoss:plugin;

interface logger {
    log: func(msg: string) -> string;
}

world plugin {
    import logger;
    export run: func(content: list<u8>, input: option<list<u8>>) -> result<list<u8>,string>;
}
