/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_workoss_boot_engine_ZenEngineLoader */

#ifndef _Included_com_workoss_boot_engine_ZenEngineLoader
#define _Included_com_workoss_boot_engine_ZenEngineLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_workoss_boot_engine_ZenEngineLoader
 * Method:    evaluate
 * Signature: ([B[BZI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_workoss_boot_engine_ZenEngineLoader_evaluate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jboolean, jint);

/*
 * Class:     com_workoss_boot_engine_ZenEngineLoader
 * Method:    validate
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_workoss_boot_engine_ZenEngineLoader_validate
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_workoss_boot_engine_ZenEngineLoader
 * Method:    expression
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_workoss_boot_engine_ZenEngineLoader_expression
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
