# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: mvn clean
      run: mvn clean -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
    - name: cd boot-storage/storage-server
      run: cd boot-storage/storage-server/
    
    - name: spring-boot build image
      run: mvn spring-boot:build-image -Pnative

    - name: Deploy oss
        uses: saltbo/uptoc@master
        with:
          driver: oss
          region: cn-shenzhen
          bucket: workoss
          exclude: .cache,test
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
      
      
      
      
        
